include:
  - project: 'gitops-demo/infra/templates'
    file: '/terraform.gitlab-ci.yml'

.secrets:
  secrets:
    GOOGLE_CREDENTIALS:
      vault: infrastructure/gcp/GOOGLE_CREDENTIALS@secret
      file: false
    GOOGLE_PROJECT:
      vault: infrastructure/gcp/GOOGLE_PROJECT@secret
      file: false
    GOOGLE_REGION:
      vault: infrastructure/gcp/GOOGLE_REGION@secret
      file: false
    GITLAB_TOKEN:
      vault: infrastructure/gitlab/GITLAB_TOKEN@secret
      file: false
